Better error reporting
armooo/suds_requests pull request #6
Opened 2017-01-16 09:21 UTC by stedi67

suds would fail in case of a network error with an unrelated
error message ('NoneType' object has no attribute 'read') in
the suds client. This patch makes the failure explicit.

2017-01-17 06:52 UTC, armooo requested changes

2017-01-17 06:52 UTC, armooo commented on setup.py
> +    version='0.3.1',
I will take care of increasing the version when make the new release on pypi.

2017-01-17 06:52 UTC, armooo commented on suds_requests.py
> +                buf,
Please update the tests in `tests/test_errors.py` to cover this new case.

2017-01-17 10:35 UTC, stedi67 commented on setup.py
> +    version='0.3.1',
o.k.

2017-01-17 10:35 UTC, stedi67 commented on suds_requests.py
> +                buf,
Sure. Sorry that I didn't do that in the first place.

2017-01-18 05:14 UTC, armooo commented
Thanks for the fix! It is up on pypi now as well.

2017-01-18 05:14 UTC, closed without merging

2017-01-18 08:20 UTC, stedi67 commented
Thanks for merging it so quickly!